create table bitacora_FechasRev(
folioProyecto int not null,
Fecha1 date,
Fecha1_nuevo date,
Fecha1_viejo date,
Fecha2 date,
Fecha2_nuevo date,
Fecha2_viejo date,
Fecha3 date,
Fecha3_nuevo date,
Fecha3_viejo date,
Fecha4 date,
Fecha4_nuevo date,
Fecha4_viejo date,
Fecha5 date,
Fecha5_nuevo date,
Fecha5_viejo date,
operacion varchar(15),
usuario varchar(10))