create table bitacora_Proyectos(
id_bitacoraPr int identity primary key,
folioProyecto int,
matriculaAlumno varchar(10),
nombreProyecto varchar(50),
nombreProyecto_nuevo varchar(50),
nombreProyecto_viejo varchar(50),
nombreEmpresa varchar(50),
nombreEmpresa_nuevo varchar(50),
nombreEmpresa_viejo varchar(50),
calificacion int,
calificacion_nuevo int,
calificacion_viejo int,
cveAsesor varchar(10),
cveAsesor_nuevo varchar(10),
cveAsesor_viejo varchar(10),
cveRevisor1 varchar(10),
cveRevisor1_nuevo varchar(10),
cveRevisor1_viejo varchar(10),
cveRevisor2 varchar(10), 
cveRevisor2_nuevo varchar(10),
cveRevisor2_viejo varchar(10),  
periodo varchar(45),
periodo_nuevo varchar(45),
periodo_viejo varchar(45),
inicio date, 
inicio_nuevo date,
inicio_viejo date,  
fin date,
fin_nuevo date,
fin_viejo date,
operacion varchar(15),
usuario varchar(10)
)