create table bitacora_Alumnos (
id_bitacora int identity, 
matricula varchar(10),
nombre varchar(30),
nombre_nuevo varchar(30),
nombre_viejo varchar(30),
apPaterno varchar(30),
apPaterno_nuevo varchar(30),
apPaterno_viejo varchar(30),
apMaterno varchar(30),
apMaterno_nuevo varchar(30),
apMaterno_viejo varchar(30),
telefono varchar(13),
telefono_nuevo varchar(13),
telefono_viejo varchar(13),
correo varchar(100),
correo_nuevo varchar(100),
correo_viejo varchar(100),
cve_carrera varchar(50),
cve_carrera_nuevo varchar(50),
cve_carrera_viejo varchar(50),
sexo char(1),
sexo_nuevo char(1),
sexo_viejo char(1),
operacion  varchar(15) not null,
cveAsesor varchar(10)
)