create table bitacora_Asesores(
id_bitacoraAs int identity primary key,
cveAsesor varchar(10),
nombre varchar(30),
nombre_nuevo varchar(30),
nombre_vieho varchar(30),
apPaterno varchar(30),
apPaterno_nuevo varchar(30),
apPaterno_viejo varchar(30),
apMaterno varchar(30),
apMaterno_nuevo varchar(30),
apMaterno_viejo varchar(30),
correo varchar(60),
correo_nuevo varchar(60),
correo_viejo varchar(60),
telefono varchar(13),
telefono_nuevo varchar(13),
telefono_viejo varchar(13),
cve_carrera varchar(15),
cve_carrera_nuevo varchar(15),
cve_carrera_viejo varchar(15),
operacion varchar(15),
usuario varchar(10))
